# Generated by Django 5.1.2 on 2024-12-09 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usm_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtendedModelUser',
        ),
    ]
